;/*FB_PKG_DELIM*/

__d("BanzaiAdapter",["cr:5866"],(function(a,b,c,d,e,f,g){g["default"]=b("cr:5866")}),98);
__d("cancelIdleCallback",["cr:7384"],(function(a,b,c,d,e,f,g){g["default"]=b("cr:7384")}),98);
__d("IdleCallbackImplementation",["performanceNow","requestAnimationFramePolyfill"],(function(a,b,c,d,e,f,g){var h,i=[],j=0,k=0,l=-1,m=!1,n=1e3/60,o=2;function p(a){return a}function q(a){return a}function b(b,c){var d=k++;i[d]=b;s();if(c!=null&&c.timeout>0){var e=p(d);a.setTimeout(function(){return y(e)},c.timeout)}return p(d)}function r(a){a=q(a);i[a]=null}function s(){m||(m=!0,c("requestAnimationFramePolyfill")(function(a){m=!1,u((h||(h=c("performanceNow")))()-a)}))}function t(a){var b=n-o;if(a<b)return b-a;a=a%n;if(a>b||a<o)return 0;else return b-a}function u(a){var b=(h||(h=c("performanceNow")))();if(b>l){a=t(a);if(a>0){b=b+a;x(b);l=b}}v()&&s()}function v(){return j<i.length}function w(){while(v()){var a=i[j];j++;if(a)return a}return null}function x(a){var b;while((h||(h=c("performanceNow")))()<a&&(b=w()))b(new z(a))}function y(a){var b=q(a);b=i[b];b&&(r(a),b(new z(null)))}var z=function(){function a(a){this.didTimeout=a==null,this.$1=a}var b=a.prototype;b.timeRemaining=function(){var a=this.$1;if(a!=null){var b=(h||(h=c("performanceNow")))();if(b<a)return a-b}return 0};return a}();g.requestIdleCallback=b;g.cancelIdleCallback=r}),98);
__d("requestIdleCallbackAcrossTransitions",["IdleCallbackImplementation","TimeSlice"],(function(a,b,c,d,e,f,g){var h=a.requestIdleCallback||d("IdleCallbackImplementation").requestIdleCallback;function b(b,d){b=c("TimeSlice").guard(b,"requestIdleCallback",{propagationType:c("TimeSlice").PropagationType.CONTINUATION,registerCallStack:!0});return h.call(a,b,d)}g["default"]=b}),98);
__d("SetIdleTimeoutAcrossTransitions",["NavigationMetrics","cancelIdleCallback","clearTimeout","nullthrows","requestIdleCallbackAcrossTransitions","setTimeoutAcrossTransitions"],(function(a,b,c,d,e,f,g){"use strict";var h=!1,i=new Map();function b(a,b){if(h){var d=c("setTimeoutAcrossTransitions")(function(){var b=c("requestIdleCallbackAcrossTransitions")(function(){a(),i["delete"](b)});i.set(d,b)},b);return d}else return c("setTimeoutAcrossTransitions")(a,b)}function d(a){c("clearTimeout")(a),i.has(a)&&(c("cancelIdleCallback")(c("nullthrows")(i.get(a))),i["delete"](a))}c("NavigationMetrics").addRetroactiveListener(c("NavigationMetrics").Events.EVENT_OCCURRED,function(b,c){c.event==="all_pagelets_loaded"&&(h=!!a.requestIdleCallback)});g.start=b;g.clear=d}),98);
__d("BanzaiWWW",["cr:1642797"],(function(a,b,c,d,e,f,g){g["default"]=b("cr:1642797")}),98);
__d("cancelIdleCallbackBlue",["IdleCallbackImplementation"],(function(a,b,c,d,e,f,g){var h=(c=a.cancelIdleCallback)!=null?c:d("IdleCallbackImplementation").cancelIdleCallback;function b(a){h(a)}g["default"]=b}),98);
__d("cancelIdleCallbackWWW",["cr:692209"],(function(a,b,c,d,e,f,g){g["default"]=b("cr:692209")}),98);